load_balancer:
  image: nginx:1.11.0
  container_name: load_balancer
  volumes:
    - ./var/nginx/conf:/etc/nginx/conf.d/
    - ./var/nginx/log:/var/log/nginx
    - ./var/ssl:/etc/nginx/ssl
  ports:
    - "80:80"
    - "443:443"
  links:
    - webserver1
    - webserver2
webserver1:
  image: httpd:2.4.20
  volumes:
    - ./var/httpd/conf:/usr/local/apache2/conf/
    - ./var/httpd/logs:/usr/local/apache2/logs/
    - ./application:/application/
  links:
    - php_server
webserver2:
  image: httpd:2.4.20
  volumes:
    - ./var/httpd/conf:/usr/local/apache2/conf/
    - ./var/httpd/logs:/usr/local/apache2/logs/
    - ./application:/application/
  links:
    - php_server
php_server:
  build: ./var/php-fpm/dockerfile/php7
  volumes:
    - ./var/php-fpm/conf:/usr/local/etc/php-fpm.d/
    - ./var/php-fpm/log:/usr/local/log/
    - ./application:/application/
  container_name: php_server
  links:
    - db
    - cache_server1
    - cache_server2
    - mail_server
    - redis_server
db:
  build: ./var/mysql/dockerfile
  volumes:
    - ./var/mysql/lib:/var/lib/mysql
    - ./var/mysql/conf:/etc/mysql
    - ./var/mysql/log:/var/log/mysql
  container_name: db
cache_server1:
  image: memcached:1.4.25
  container_name: cache_server1
cache_server2:
  image: memcached:1.4.25
  container_name: cache_server2
mail_server:
  image: tozd/postfix
  container_name: mail_server
  volumes:
    - ./var/postfix/spool/postfix:/var/spool/postfix
redis_server:
  image: redis:3.2.3
  ports:
    - "6379:6379"
  volumes:
    - ./var/redis/data:/data/
  container_name: redis_server
